### ISSUE TITLE
Last modified time not shown correctly in blist file box

### ISSUE THREAD

**Issue by jthelin** [jthelin/blist#57]
The last modified time not shown correctly in blist file box.

Example:
```
************************************************
* File name: D:/a/1/s/blist_version.h          *
* Last modified: Tue Sep 12 20:52:14 2389  ρu *
* File size (bytes): 557                       *
************************************************
```

**Comment by jthelin** [comment]
```
==277854==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd8c03b99a at pc 0x000000431ad9 bp 0x7ffd8c03b840 sp 0x7ffd8c03b000
[ctest] READ of size 28 at 0x7ffd8c03b99a thread T0
[ctest]     #0 0x431ad8 in strlen (/home/njt/Depot/SwTech/blist/build/src/blist+0x431ad8)
[ctest]     #1 0x4ccead in std::char_traits<char>::length(char const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/char_traits.h:357:9
[ctest]     #2 0x4cacd6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:527:39
[ctest]     #3 0x4d7f10 in FileUtils::GetModificationDate(std::filesystem::__cxx11::path const&) /home/njt/Depot/SwTech/blist/build/../libsrc/fileutil.cc:31:18
[ctest]     #4 0x4d0bbc in File::ModificationDate[abi:cxx11]() const /home/njt/Depot/SwTech/blist/build/../libsrc/File.cc:38:10
[ctest]     #5 0x4d106a in File::FileInfo[abi:cxx11]() const /home/njt/Depot/SwTech/blist/build/../libsrc/File.cc:50:37
[ctest]     #6 0x4ca131 in ProcessFile(File&, blist_params const&, std::ostream&) /home/njt/Depot/SwTech/blist/build/../src/blist.cc:105:28
[ctest]     #7 0x4caa87 in blist_main(int, char**) /home/njt/Depot/SwTech/blist/build/../src/blist.cc:151:7
[ctest]     #8 0x4cac21 in main /home/njt/Depot/SwTech/blist/build/../src/blist.cc:166:10
[ctest]     #9 0x7f1cddc130b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16
[ctest]     #10 0x41eead in _start (/home/njt/Depot/SwTech/blist/build/src/blist+0x41eead)
[ctest] 
[ctest] Address 0x7ffd8c03b99a is located in stack of thread T0 at offset 186 in frame
[ctest]     #0 0x4d7bef in FileUtils::GetModificationDate(std::filesystem::__cxx11::path const&) /home/njt/Depot/SwTech/blist/build/../libsrc/fileutil.cc:10
[ctest] 
[ctest]   This frame has 5 object(s):
[ctest]     [32, 40) 'timestamp' (line 11)
[ctest]     [64, 120) 'time' (line 13)
[ctest]     [160, 186) 'time_str' (line 15) <== Memory access at offset 186 overflows this variable
[ctest]     [224, 256) 'modTime' (line 31)
[ctest]     [288, 289) 'ref.tmp' (line 31)
[ctest] HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
[ctest]       (longjmp and C++ exceptions *are* supported)
[ctest] SUMMARY: AddressSanitizer: stack-buffer-overflow (/home/njt/Depot/SwTech/blist/build/src/blist+0x431ad8) in strlen
[ctest] Shadow bytes around the buggy address:
[ctest]   0x1000317ff6e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ctest]   0x1000317ff6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ctest]   0x1000317ff700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ctest]   0x1000317ff710: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
[ctest]   0x1000317ff720: 00 f2 f2 f2 00 00 00 00 00 00 00 f2 f2 f2 f2 f2
[ctest] =>0x1000317ff730: 00 00 00[02]f2 f2 f2 f2 00 00 00 00 f2 f2 f2 f2
[ctest]   0x1000317ff740: 01 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
[ctest]   0x1000317ff750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ctest]   0x1000317ff760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ctest]   0x1000317ff770: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 00 00 00 00
[ctest]   0x1000317ff780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ctest] Shadow byte legend (one shadow byte represents 8 application bytes):
[ctest]   Addressable:           00
[ctest]   Partially addressable: 01 02 03 04 05 06 07 
[ctest]   Heap left redzone:       fa
[ctest]   Freed heap region:       fd
[ctest]   Stack left redzone:      f1
[ctest]   Stack mid redzone:       f2
[ctest]   Stack right redzone:     f3
[ctest]   Stack after return:      f5
[ctest]   Stack use after scope:   f8
[ctest]   Global redzone:          f9
[ctest]   Global init order:       f6
[ctest]   Poisoned by user:        f7
[ctest]   Container overflow:      fc
[ctest]   Array cookie:            ac
[ctest]   Intra object redzone:    bb
[ctest]   ASan internal:           fe
[ctest]   Left alloca redzone:     ca
[ctest]   Right alloca redzone:    cb
[ctest]   Shadow gap:              cc
[ctest] ==277854==ABORTING
```
